const { SlashCommandBuilder, EmbedBuilder, PermissionFlagsBits } = require('discord.js');
const axios = require('axios');

module.exports = [
  { data: new SlashCommandBuilder().setName('8ball').setDescription('Ask the magic 8-ball').addStringOption(o => o.setName('question').setDescription('Question').setRequired(true)), async execute(interaction) { const answers = ['Yes.', 'No.', 'Probably.', 'Probably not.', 'Ask again later.', 'There is not enough information.']; return interaction.reply({ embeds: [new EmbedBuilder().setColor(0x5865f2).setTitle('8-ball').addFields({ name: 'Question', value: interaction.options.getString('question') }, { name: 'Answer', value: answers[Math.floor(Math.random() * answers.length)] })] }); } },
  { data: new SlashCommandBuilder().setName('roll').setDescription('Roll a number').addIntegerOption(o => o.setName('sides').setDescription('Number of sides').setMinValue(2).setMaxValue(1000)), async execute(interaction) { const sides = interaction.options.getInteger('sides') || 100; return interaction.reply(`You rolled ${Math.floor(Math.random() * sides) + 1} on a ${sides}-sided die.`); } },
  { data: new SlashCommandBuilder().setName('coinflip').setDescription('Flip a coin'), async execute(interaction) { return interaction.reply(`The coin landed on ${Math.random() < 0.5 ? 'heads' : 'tails'}.`); } },
  { data: new SlashCommandBuilder().setName('rps').setDescription('Play rock paper scissors').addStringOption(o => o.setName('choice').setDescription('Your choice').setRequired(true).addChoices({ name: 'Rock', value: 'rock' }, { name: 'Paper', value: 'paper' }, { name: 'Scissors', value: 'scissors' })), async execute(interaction) { const userChoice = interaction.options.getString('choice'); const botChoice = ['rock', 'paper', 'scissors'][Math.floor(Math.random() * 3)]; const win = (userChoice === 'rock' && botChoice === 'scissors') || (userChoice === 'paper' && botChoice === 'rock') || (userChoice === 'scissors' && botChoice === 'paper'); const result = userChoice === botChoice ? 'Draw.' : win ? 'You win.' : 'You lose.'; return interaction.reply({ embeds: [new EmbedBuilder().setColor(0x5865f2).setTitle('Rock paper scissors').setDescription(`You chose ${userChoice}. I chose ${botChoice}.\n${result}`)] }); } },
  { data: new SlashCommandBuilder().setName('meme').setDescription('Fetch a random meme'), async execute(interaction) { await interaction.deferReply(); try { const response = await axios.get('https://meme-api.com/gimme', { timeout: 8000 }); const meme = response.data; return interaction.editReply({ embeds: [new EmbedBuilder().setColor(0x5865f2).setTitle(meme.title).setURL(meme.postLink).setImage(meme.url).setFooter({ text: `From r/${meme.subreddit}` })] }); } catch { return interaction.editReply('The meme service is unavailable right now.'); } } },
  { data: new SlashCommandBuilder().setName('quote').setDescription('Get an inspirational quote'), async execute(interaction) { await interaction.deferReply(); try { const response = await axios.get('https://api.quotable.io/random', { timeout: 8000 }); return interaction.editReply({ embeds: [new EmbedBuilder().setColor(0x5865f2).setDescription(`"${response.data.content}"`).setFooter({ text: response.data.author })] }); } catch { return interaction.editReply('The quote service is unavailable right now.'); } } },
  { data: new SlashCommandBuilder().setName('dice').setDescription('Roll multiple dice').addIntegerOption(o => o.setName('count').setDescription('Number of dice').setRequired(true).setMinValue(1).setMaxValue(20)).addIntegerOption(o => o.setName('sides').setDescription('Sides per die').setRequired(true).setMinValue(2).setMaxValue(100)), async execute(interaction) { const count = interaction.options.getInteger('count'); const sides = interaction.options.getInteger('sides'); const rolls = Array.from({ length: count }, () => Math.floor(Math.random() * sides) + 1); return interaction.reply(`Rolls: ${rolls.join(', ')} | Total: ${rolls.reduce((sum, value) => sum + value, 0)}`); } },
  { data: new SlashCommandBuilder().setName('rate').setDescription('Rate something').addStringOption(o => o.setName('thing').setDescription('Thing to rate').setRequired(true)), async execute(interaction) { return interaction.reply(`${interaction.options.getString('thing')} gets ${Math.floor(Math.random() * 101)}/100.`); } },
  { data: new SlashCommandBuilder().setName('say').setDescription('Make the bot say something').setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addStringOption(o => o.setName('message').setDescription('Message').setRequired(true).setMaxLength(2000)), async execute(interaction) { const message = interaction.options.getString('message'); await interaction.reply({ content: 'Message sent.', ephemeral: true }); return interaction.channel.send({ content: message, allowedMentions: { parse: [] } }); } },
  { data: new SlashCommandBuilder().setName('reverse').setDescription('Reverse text').addStringOption(o => o.setName('text').setDescription('Text').setRequired(true).setMaxLength(2000)), async execute(interaction) { return interaction.reply(interaction.options.getString('text').split('').reverse().join('')); } }
];
