const { SlashCommandBuilder, EmbedBuilder, PermissionFlagsBits } = require('discord.js');
const axios = require('axios');
const { weatherApiKey } = require('../config');
const { getXp, getMemberStats } = require('../utils');
const { isXpAdmin } = require('../auth');

function levelForXp(xp) {
  return Math.floor(Math.sqrt(xp / 100)) + 1;
}

function voiceMinutes(stats) {
  const currentSeconds = stats.voiceStartedAt ? (Date.now() - stats.voiceStartedAt) / 1000 : 0;
  return Math.floor((stats.voiceSeconds + currentSeconds) / 60);
}

module.exports = [
  { data: new SlashCommandBuilder().setName('help').setDescription('List available commands'), async execute(interaction) { const groups = { Moderation: ['ban', 'kick', 'timeout', 'untimeout', 'purge', 'lockdown', 'unlock', 'slowmode', 'nick', 'role-add', 'role-remove', 'warn', 'warnings', 'clearwarns', 'ticket-setup'], Verification: ['verify-setup', 'role-info', 'autorole-set', 'reaction-role', 'members-with-role'], Utility: ['ping', 'userinfo', 'serverinfo', 'avatar', 'botinfo', 'channelinfo', 'banner', 'uptime', 'embed', 'poll'], Fun: ['8ball', 'roll', 'coinflip', 'rps', 'meme', 'quote', 'dice', 'rate', 'say', 'reverse'], Information: ['help', 'weather', 'math', 'define', 'urban', 'wikipedia', 'github', 'translate', 'stats', 'invites'], XP: ['xp', 'xpgive', 'xpset', 'xpleaderboard', 'xp-rank'] }; if (!isXpAdmin(interaction.member)) delete groups.XP; return interaction.reply({ embeds: [new EmbedBuilder().setColor(0x5865f2).setTitle('Command list').setDescription(Object.entries(groups).map(([name, commands]) => `**${name}**\n${commands.map(command => `/${command}`).join(', ')}`).join('\n\n'))] }); } },
  { data: new SlashCommandBuilder().setName('weather').setDescription('Get current weather').addStringOption(o => o.setName('city').setDescription('City').setRequired(true)), async execute(interaction) { if (!weatherApiKey) return interaction.reply({ content: 'Weather API key is not configured.', ephemeral: true }); await interaction.deferReply(); try { const city = interaction.options.getString('city'); const response = await axios.get('https://api.openweathermap.org/data/2.5/weather', { params: { q: city, appid: weatherApiKey, units: 'metric' }, timeout: 8000 }); const data = response.data; return interaction.editReply({ embeds: [new EmbedBuilder().setColor(0x2563eb).setTitle(`Weather in ${data.name}`).addFields({ name: 'Conditions', value: data.weather[0].description, inline: true }, { name: 'Temperature', value: `${data.main.temp} C`, inline: true }, { name: 'Feels like', value: `${data.main.feels_like} C`, inline: true }, { name: 'Humidity', value: `${data.main.humidity}%`, inline: true })] }); } catch { return interaction.editReply('The city could not be found or the weather service is unavailable.'); } } },
  { data: new SlashCommandBuilder().setName('math').setDescription('Calculate a basic expression').addStringOption(o => o.setName('expression').setDescription('Expression using numbers and + - * / % ( )').setRequired(true).setMaxLength(100)), async execute(interaction) { const expression = interaction.options.getString('expression'); if (!/^[0-9+\-*/%().\s]+$/.test(expression)) return interaction.reply({ content: 'Only numbers and basic arithmetic operators are allowed.', ephemeral: true }); try { const result = Function(`"use strict"; return (${expression})`)(); if (!Number.isFinite(result)) throw new Error('Invalid result'); return interaction.reply(`${expression} = ${result}`); } catch { return interaction.reply({ content: 'That expression is invalid.', ephemeral: true }); } } },
  { data: new SlashCommandBuilder().setName('define').setDescription('Define an English word').addStringOption(o => o.setName('word').setDescription('Word').setRequired(true)), async execute(interaction) { await interaction.deferReply(); try { const word = interaction.options.getString('word'); const response = await axios.get(`https://api.dictionaryapi.dev/api/v2/entries/en/${encodeURIComponent(word)}`, { timeout: 8000 }); const entry = response.data[0]; const meaning = entry.meanings[0]; return interaction.editReply({ embeds: [new EmbedBuilder().setColor(0x5865f2).setTitle(entry.word).setDescription(meaning.definitions.slice(0, 5).map((definition, index) => `${index + 1}. ${definition.definition}`).join('\n'))] }); } catch { return interaction.editReply('No definition was found.'); } } },
  { data: new SlashCommandBuilder().setName('urban').setDescription('Search Urban Dictionary').addStringOption(o => o.setName('term').setDescription('Term').setRequired(true)), async execute(interaction) { await interaction.deferReply(); try { const response = await axios.get('https://api.urbandictionary.com/v0/define', { params: { term: interaction.options.getString('term') }, timeout: 8000 }); const result = response.data.list[0]; if (!result) return interaction.editReply('No definition was found.'); return interaction.editReply({ embeds: [new EmbedBuilder().setColor(0xf59f00).setTitle(result.word).setDescription(result.definition.slice(0, 4000)).setURL(result.permalink)] }); } catch { return interaction.editReply('Urban Dictionary is unavailable right now.'); } } },
  { data: new SlashCommandBuilder().setName('wikipedia').setDescription('Search Wikipedia').addStringOption(o => o.setName('query').setDescription('Search query').setRequired(true)), async execute(interaction) { await interaction.deferReply(); try { const query = interaction.options.getString('query'); const response = await axios.get('https://en.wikipedia.org/api/rest_v1/page/summary/' + encodeURIComponent(query), { timeout: 8000 }); return interaction.editReply({ embeds: [new EmbedBuilder().setColor(0x5865f2).setTitle(response.data.title).setURL(response.data.content_urls.desktop.page).setDescription(response.data.extract?.slice(0, 4000) || 'No summary available.')] }); } catch { return interaction.editReply('No Wikipedia article was found.'); } } },
  { data: new SlashCommandBuilder().setName('github').setDescription('Show a GitHub repository').addStringOption(o => o.setName('repository').setDescription('owner/repository or search').setRequired(true)), async execute(interaction) { await interaction.deferReply(); try { const rawInput = interaction.options.getString('repository').trim(); if (!rawInput) return interaction.editReply('Enter a repository name, GitHub URL, or search term.'); const input = rawInput.replace(/^https?:\/\/github\.com\//i, '').replace(/\.git$/i, '').replace(/\/$/, ''); const headers = { 'User-Agent': 'discord-security-bot', Accept: 'application/vnd.github+json' }; let repo; if (/^[^/\s]+\/[^/\s]+$/.test(input)) { repo = (await axios.get(`https://api.github.com/repos/${input}`, { timeout: 8000, headers })).data; } else { const results = (await axios.get('https://api.github.com/search/repositories', { params: { q: input, sort: 'stars', order: 'desc', per_page: 1 }, timeout: 8000, headers })).data.items; repo = results?.[0]; } if (!repo) return interaction.editReply('No GitHub repository matched that search.'); return interaction.editReply({ embeds: [new EmbedBuilder().setColor(0x24292f).setTitle(repo.full_name).setURL(repo.html_url).setDescription(repo.description || 'No description.').addFields({ name: 'Stars', value: String(repo.stargazers_count), inline: true }, { name: 'Forks', value: String(repo.forks_count), inline: true }, { name: 'Open issues', value: String(repo.open_issues_count), inline: true })] }); } catch (error) { const status = error.response?.status; if (status === 403 || status === 429) return interaction.editReply('GitHub search is rate-limited right now. Try again later.'); if (status === 404) return interaction.editReply('That GitHub repository was not found.'); console.error('github command failed:', error.message); return interaction.editReply('GitHub is unavailable right now.'); } } },
  { data: new SlashCommandBuilder().setName('translate').setDescription('Translate text').addStringOption(o => o.setName('text').setDescription('Text').setRequired(true)).addStringOption(o => o.setName('language').setDescription('Target language code such as es or fr').setRequired(true)), async execute(interaction) { await interaction.deferReply(); try { const response = await axios.post('https://libretranslate.de/translate', { q: interaction.options.getString('text'), source: 'auto', target: interaction.options.getString('language'), format: 'text' }, { timeout: 10000 }); return interaction.editReply({ embeds: [new EmbedBuilder().setColor(0x5865f2).setTitle('Translation').setDescription(response.data.translatedText)] }); } catch { return interaction.editReply('Translation is unavailable right now.'); } } },
  { data: new SlashCommandBuilder().setName('stats').setDescription('Show your activity statistics'), async execute(interaction) { const stats = getMemberStats(interaction.guild.id, interaction.user.id); const xp = getXp(interaction.guild.id, interaction.user.id); return interaction.reply({ embeds: [new EmbedBuilder().setColor(0x5865f2).setTitle(`${interaction.user.username}'s stats`).setThumbnail(interaction.user.displayAvatarURL({ size: 128 })).addFields({ name: 'XP', value: String(xp), inline: true }, { name: 'Level', value: String(levelForXp(xp)), inline: true }, { name: 'Messages', value: String(stats.messages), inline: true }, { name: 'Voice time', value: `${voiceMinutes(stats)} minutes`, inline: true })] }); } },
  { data: new SlashCommandBuilder().setName('invites').setDescription('List server invites').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild), async execute(interaction) { const invites = await interaction.guild.invites.fetch(); const text = invites.size ? invites.map(invite => `${invite.code} - ${invite.uses || 0} uses - ${invite.inviter?.tag || 'Unknown'}`).join('\n') : 'No active invites.'; return interaction.reply({ embeds: [new EmbedBuilder().setColor(0x5865f2).setTitle('Server invites').setDescription(text.slice(0, 4000))], ephemeral: true }); } }
];
