const { SlashCommandBuilder, EmbedBuilder, PermissionFlagsBits, ChannelType } = require('discord.js');
const { formatDuration, successEmbed, errorEmbed } = require('../utils');

module.exports = [
  { data: new SlashCommandBuilder().setName('ping').setDescription('Show bot latency'), async execute(interaction) { const sent = await interaction.reply({ content: 'Checking latency...', fetchReply: true }); return interaction.editReply(`WebSocket: ${interaction.client.ws.ping}ms | Round trip: ${sent.createdTimestamp - interaction.createdTimestamp}ms`); } },
  { data: new SlashCommandBuilder().setName('userinfo').setDescription('Show user information').addUserOption(o => o.setName('user').setDescription('User')), async execute(interaction) { const user = interaction.options.getUser('user') || interaction.user; const member = await interaction.guild.members.fetch(user.id).catch(() => null); return interaction.reply({ embeds: [new EmbedBuilder().setColor(0x5865f2).setTitle(user.tag).setThumbnail(user.displayAvatarURL({ size: 256 })).addFields({ name: 'User ID', value: user.id, inline: true }, { name: 'Created', value: `<t:${Math.floor(user.createdTimestamp / 1000)}:F>`, inline: true }, { name: 'Joined', value: member?.joinedTimestamp ? `<t:${Math.floor(member.joinedTimestamp / 1000)}:F>` : 'Unknown', inline: true }, { name: 'Roles', value: member ? member.roles.cache.filter(role => role.id !== interaction.guild.id).map(role => role.toString()).join(', ') || 'None' : 'Unknown' })] }); } },
  { data: new SlashCommandBuilder().setName('serverinfo').setDescription('Show server information'), async execute(interaction) { const guild = interaction.guild; return interaction.reply({ embeds: [new EmbedBuilder().setColor(0x5865f2).setTitle(guild.name).setThumbnail(guild.iconURL({ size: 256 })).addFields({ name: 'Owner', value: `<@${guild.ownerId}>`, inline: true }, { name: 'Members', value: String(guild.memberCount), inline: true }, { name: 'Channels', value: String(guild.channels.cache.size), inline: true }, { name: 'Roles', value: String(guild.roles.cache.size), inline: true }, { name: 'Created', value: `<t:${Math.floor(guild.createdTimestamp / 1000)}:D>`, inline: true })] }); } },
  { data: new SlashCommandBuilder().setName('avatar').setDescription('Show a user avatar').addUserOption(o => o.setName('user').setDescription('User')), async execute(interaction) { const user = interaction.options.getUser('user') || interaction.user; return interaction.reply({ embeds: [new EmbedBuilder().setColor(0x5865f2).setTitle(`${user.tag}'s avatar`).setImage(user.displayAvatarURL({ size: 1024, extension: 'png' }))] }); } },
  { data: new SlashCommandBuilder().setName('botinfo').setDescription('Show bot information'), async execute(interaction) { return interaction.reply({ embeds: [new EmbedBuilder().setColor(0x5865f2).setTitle(interaction.client.user.tag).setThumbnail(interaction.client.user.displayAvatarURL()).addFields({ name: 'Servers', value: String(interaction.client.guilds.cache.size), inline: true }, { name: 'Users', value: String(interaction.client.guilds.cache.reduce((total, guild) => total + guild.memberCount, 0)), inline: true }, { name: 'Uptime', value: formatDuration(interaction.client.uptime), inline: true })] }); } },
  { data: new SlashCommandBuilder().setName('channelinfo').setDescription('Show channel information').addChannelOption(o => o.setName('channel').setDescription('Channel')), async execute(interaction) { const channel = interaction.options.getChannel('channel') || interaction.channel; return interaction.reply({ embeds: [new EmbedBuilder().setColor(0x5865f2).setTitle(channel.name).addFields({ name: 'ID', value: channel.id, inline: true }, { name: 'Type', value: ChannelType[channel.type] || String(channel.type), inline: true }, { name: 'Created', value: `<t:${Math.floor(channel.createdTimestamp / 1000)}:F>`, inline: true }, { name: 'Topic', value: 'topic' in channel ? channel.topic || 'None' : 'None' })] }); } },
  { data: new SlashCommandBuilder().setName('banner').setDescription('Show a user banner').addUserOption(o => o.setName('user').setDescription('User')), async execute(interaction) { const user = await (interaction.options.getUser('user') || interaction.user).fetch(); if (!user.banner) return interaction.reply({ embeds: [errorEmbed('That user does not have a banner.')], ephemeral: true }); return interaction.reply({ embeds: [new EmbedBuilder().setColor(0x5865f2).setTitle(`${user.tag}'s banner`).setImage(user.bannerURL({ size: 1024 }))] }); } },
  { data: new SlashCommandBuilder().setName('uptime').setDescription('Show bot uptime'), async execute(interaction) { return interaction.reply(`Uptime: ${formatDuration(interaction.client.uptime)}`); } },
  { data: new SlashCommandBuilder().setName('embed').setDescription('Send an embed').setDefaultMemberPermissions(PermissionFlagsBits.ManageMessages).addStringOption(o => o.setName('title').setDescription('Title').setRequired(true).setMaxLength(256)).addStringOption(o => o.setName('description').setDescription('Description').setRequired(true).setMaxLength(4000)).addStringOption(o => o.setName('color').setDescription('Hex color such as #5865f2')), async execute(interaction) { const rawColor = interaction.options.getString('color') || '#5865f2'; const color = /^#[0-9a-f]{6}$/i.test(rawColor) ? rawColor : '#5865f2'; await interaction.channel.send({ embeds: [new EmbedBuilder().setColor(color).setTitle(interaction.options.getString('title')).setDescription(interaction.options.getString('description'))] }); return interaction.reply({ embeds: [successEmbed('Embed sent', 'The embed was posted in this channel.')], ephemeral: true }); } },
  { data: new SlashCommandBuilder().setName('poll').setDescription('Create a yes/no poll').addStringOption(o => o.setName('question').setDescription('Question').setRequired(true).setMaxLength(1000)), async execute(interaction) { await interaction.channel.send({ embeds: [new EmbedBuilder().setColor(0x2563eb).setTitle('Poll').setDescription(`${interaction.options.getString('question')}\n\nReply with 1 for yes or 2 for no.`)] }); return interaction.reply({ content: 'Poll created.', ephemeral: true }); } }
];
